[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "diffhydro"
version = "0.1.0"
description = "Differentiable hydrodynamics in JAX with pluggable gravity and other goodies"
readme = "README.md"
requires-python = ">=3.0"
license = { file = "LICENSE" }
authors = [{ name = "Benjamin Horowitz", email = "horowitz.ben@gmail.com" }]
keywords = ["jax", "hydrodynamics", "numerical-methods", "mhd", "ctu", "ct"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: Physics",
  "Typing :: Typed"
]

# Keep heavy deps optional so users can choose CPU/GPU JAX wheels
dependencies = [
  "numpy>=1.26",
]

[project.optional-dependencies]
jax = [
  # Users pick correct jaxlib wheel for CPU/CUDA/ROCm
  "jax>=0.4.0",
]
dev = [
  "pytest>=8",
  "pytest-cov>=5",
  "ruff>=0.5",
  "mypy>=1.11",
  "pre-commit>=4",
]
mhd = [
  # future add-ons (e.g., HLLD, CT helpers) can live here
]

[project.urls]
Homepage = "https://github.com/your-org/diffhydro"
Issues = "https://github.com/your-org/diffhydro/issues"

[tool.hatch.build.targets.wheel]
packages = ["diffhydro"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.mypy]
python_version = "3.10"
warn_unused_ignores = true
strict = true
packages = ["diffhydro"]